# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(854, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_users = QtWidgets.QListWidget(self.frame)
        self.listWidget_users.setObjectName("listWidget_users")
        self.verticalLayout.addWidget(self.listWidget_users)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_chat_with = QtWidgets.QLabel(self.frame_2)
        self.label_chat_with.setObjectName("label_chat_with")
        self.verticalLayout_2.addWidget(self.label_chat_with)
        self.textEdit_chat = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_chat.setReadOnly(True)
        self.textEdit_chat.setObjectName("textEdit_chat")
        self.verticalLayout_2.addWidget(self.textEdit_chat)
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_attach = QtWidgets.QPushButton(self.widget)
        self.pushButton_attach.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/paper-clip.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_attach.setIcon(icon)
        self.pushButton_attach.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_attach.setObjectName("pushButton_attach")
        self.horizontalLayout_3.addWidget(self.pushButton_attach)
        self.textEdit_message = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_message.sizePolicy().hasHeightForWidth())
        self.textEdit_message.setSizePolicy(sizePolicy)
        self.textEdit_message.setMinimumSize(QtCore.QSize(0, 50))
        self.textEdit_message.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit_message.setObjectName("textEdit_message")
        self.horizontalLayout_3.addWidget(self.textEdit_message)
        self.pushButton_send = QtWidgets.QPushButton(self.widget)
        self.pushButton_send.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/send.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_send.setIcon(icon1)
        self.pushButton_send.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout_3.addWidget(self.pushButton_send)
        self.verticalLayout_2.addWidget(self.widget)
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 50)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 854, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_chat_with.setText(_translate("MainWindow", "Suhbatdoshni tanlang..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
