; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0A74074B-7387-4DF2-A8A3-CE6EC3D81957}
AppName=¿ ’”
AppVerName=¿ ’” 2,0
AppPublisher=¿“Ã
DefaultDirName={pf}\¿ ’”
DefaultGroupName=¿ ’”
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Õ»–\2013-2014\›ƒ\œÓÂÍÚ˚\EXE\¿ ’”\Navigator.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Õ»–\2013-2014\›ƒ\œÓÂÍÚ˚\EXE\¿ ’”\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\¿ ’”"; Filename: "{app}\Navigator.exe"
Name: "{commondesktop}\¿ ’”"; Filename: "{app}\Navigator.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Navigator.exe"; Description: "{cm:LaunchProgram,¿ ’”}"; Flags: nowait postinstall skipifsilent

